version: '3.8'

name: mondu-plugins
services:
  nginx:
    image: nginx:alpine
    networks:
      - app-network
    volumes:
      - ./apps:/usr/share/nginx/html/
      - ./nginx:/etc/nginx/conf.d
    ports:
      - '80:80'
    depends_on:
      - php-fpm
      - apache
  php70-fpm:
    build:
      context: ./images/php-fpm
      dockerfile: Dockerfile70
    networks:
      - app-network
    volumes:
      - ./apps:/usr/share/nginx/html
      - ./images/php-fpm/memory.ini:/usr/local/etc/php/conf.d/memory.ini
      - ./images/php-fpm/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
  php-fpm:
    ports:
      - '8000:8000'
    build:
      context: ./images/php-fpm
      dockerfile: Dockerfile
    networks:
      - app-network
    volumes:
      - ./apps:/usr/share/nginx/html/
      - ./commands/install_shopware5:/usr/local/bin/install_shopware5
      - ./commands/install_magento:/usr/local/bin/install_magento
      - ./commands/install_shopware6:/usr/local/bin/install_shopware6
      - ./commands/install_jtl5:/usr/local/bin/install_jtl5
      - ./commands/install_woocommerce:/usr/local/bin/install_woocommerce
      - ./commands/install_woocommerce82:/usr/local/bin/install_woocommerce82
      - ./commands/install_oxid:/usr/local/bin/install_oxid
      - ./images/php-fpm/memory.ini:/usr/local/etc/php/conf.d/memory.ini
      - ./images/php-fpm/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
  # for jtl5 shop...
#  apache:
#    build:
#      context: ./images/apache
#    networks:
#      - app-network
#    volumes:
#      - ./apps/jtl5:/var/www/html/
#      - ./images/apache/additional.ini:/usr/local/etc/php/conf.d/additional.ini
#    environment:
#      - APACHE_DOCUMENT_ROOT="/var/www/html"
#   for oxid shop...
  apache:
    build:
      context: ./images/apache
    networks:
      - app-network
    volumes:
      - ./apps/oxid:/var/www/html/
      - ./images/apache/additional.ini:/usr/local/etc/php/conf.d/additional.ini
    environment:
      - APACHE_DOCUMENT_ROOT="/var/www/html/source"
  mysql57:
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3357:3306'
    networks:
      - app-network
    command: --init-file /data/application/init.sql
    volumes:
      - mysql57_data:/var/lib/mysql
      - ./images/mysql/init.sql:/data/application/init.sql
  mysql:
    image: mysql/mysql-server
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    networks:
      - app-network
    command: --init-file /data/application/init.sql
    volumes:
      - mysql_data:/var/lib/mysql
      - ./images/mysql/init.sql:/data/application/init.sql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    networks:
      - app-network
    ports:
      - "9090:80"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    networks:
      - app-network
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node

volumes:
  mysql_data:
  mysql57_data:

networks:
  app-network:
