version: '3.8'

name: mondu-plugins
services:
  nginx:
    image: nginx:alpine
    networks:
      - app-network
    volumes:
      - ./apps:/usr/share/nginx/html/
      - ./nginx:/etc/nginx/conf.d
    ports:
      - '80:80'
  php-fpm:
    build:
      context: ./images/php-fpm
      dockerfile: Dockerfile
    networks:
      - app-network
    volumes:
      - ./apps:/usr/share/nginx/html/
      - ./commands/install_shopware5:/usr/local/bin/install_shopware5
      - ./commands/install_magento:/usr/local/bin/install_magento
      - ./commands/install_shopware6:/usr/local/bin/install_shopware6
      - ./commands/install_jtl5:/usr/local/bin/install_jtl5
      - ./images/php-fpm/memory.ini:/usr/local/etc/php/conf.d/memory.ini
  # for jtl5 shop...
  apache:
    build:
      context: ./images/apache
    networks:
      - app-network
    volumes:
      - ./apps/jtl5:/var/www/html/
      - ./images/apache/additional.ini:/usr/local/etc/php/conf.d/additional.ini
  mysql:
    image: mysql/mysql-server
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    networks:
      - app-network
    command: --init-file /data/application/init.sql
    volumes:
      - mysql_data:/var/lib/mysql
      - ./images/mysql/init.sql:/data/application/init.sql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    networks:
      - app-network
    ports:
      - "8081:80"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    networks:
      - app-network
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node

volumes:
  mysql_data:

networks:
  app-network:
