#!/usr/bin/env bash

docker exec -it mondu-plugins-php-fpm-1 install_jtl5 && \
docker exec -it mondu-plugins-php-fpm-1 install_shopware6 && \
docker exec -it mondu-plugins-php-fpm-1 install_shopware5 && \
docker exec -it mondu-plugins-php-fpm-1 install_magento
