CREATE DATABASE IF NOT EXISTS magento2;
CREATE DATABASE IF NOT EXISTS jtl5;
CREATE DATABASE IF NOT EXISTS shopware6;
CREATE DATABASE IF NOT EXISTS shopware5;
CREATE DATABASE IF NOT EXISTS wordpress;
CREATE DATABASE IF NOT EXISTS woocommerce82;